# Change these first
owner: targed # Your GitHub organization or username, where this repository lives
repo: GPT-Plugins # The name of this repository

sites:
  - name: Academic_research_engine
    url: https://oa.mg/.well-known/ai-plugin.json
  - name: APIs.guru
    url: https://apis.guru/.well-known/ai-plugin.json
  - name: Appypie
    url: https://www.appypie.com/.well-known/ai-plugin.json
  - name: Asana
    url: https://app.asana.com/.well-known/ai-plugin.json
  - name: ASCIIArt
    url: https://chatgpt-plugin-ts.transitive-bullshit.workers.dev/.well-known/ai-plugin.json
  - name: Babyagichatgpt
    url: https://babyagichatgpt.skirano.repl.co/.well-known/ai-plugin.json
  - name: Biztoc
    url: https://biztoc.com/.well-known/ai-plugin.json
  - name: Boxil
    url: https://boxil.jp/.well-known/ai-plugin.json
  - name: Boxon
    url: https://www.boxon.com/.well-known/ai-plugin.json
  - name: Brainlox
    url: https://brainlox.ai/.well-known/ai-plugin.json
  - name: Broadway
    url: https://www.broadway.com/.well-known/ai-plugin.json
  - name: Bundlejs
    url: https://deno.bundlejs.com/.well-known/ai-plugin.json
  - name: Calculator
    url: https://chat-calculator-plugin.supportmirage.repl.co/.well-known/ai-plugin.json
  - name: Capcut
    url: https://www.capcut.com/.well-known/ai-plugin.json
  - name: Coderpad
    url: https://app.coderpad.io/.well-known/ai-plugin.json
  - name: Coupert
    url: https://www.coupert.com/.well-known/ai-plugin.json
  - name: Coursehero
    url: https://www.coursehero.com/.well-known/ai-plugin.json
  - name: Coursera
    url: https://www.coursera.com/.well-known/ai-plugin.json
  - name: Crane Pumps Manuals
    url: https://www.cranepumps.com/.well-known/ai-plugin.json
  - name: Creaticode
    url: https://openai.creaticode.com/.well-known/ai-plugin.json
  - name: Crossmint
    url: https://www.crossmint.com/.well-known/ai-plugin.json
  - name: DALL-E
    url: https://api.openai.com/.well-known/ai-plugin.json
  - name: Datamuse
    url: https://datamuse.com/.well-known/ai-plugin.json
  - name: Datasette
    url: https://datasette.io/.well-known/ai-plugin.json
  - name: Decisionjournal
    url: https://decisionjournalapp.com/.well-known/ai-plugin.json
  - name: Dev
    url: https://dev.to/.well-known/ai-plugin.json
  - name: Dexa Lex Fridman
    url: https://chatgpt-plugin-dexa-lex-fridman.transitive-bullshit.workers.dev/.well-known/ai-plugin.json
  - name: Docsbot
    url: https://docsbot.ai/.well-known/ai-plugin.json
  - name: Doordash
    url: https://consumer-mobile-bff.doordash.com/v1/aichat/static/ai-plugin.json
  - name: Edmunds
    url: https://api.edmunds.com/.well-known/ai-plugin.json
  - name: Freetv
    url: https://www.freetv-app.com/.well-known/ai-plugin.json
  - name: Getit
    url: https://api.getit.ai/.well_known/ai-plugin.json
  - name: GitHub **UNOFFICIAL**
    url: https://gh-plugin.teammait.com/.well-known/ai-plugin.json
  - name: Gochitchat
    url: https://gochitchat.ai/.well-known/ai-plugin.json
  - name: gofynd
    url: https://www.gofynd.com/ext/chatgpt-plugin/application/api/v1.0/.well-known/ai-plugin.json
  - name: Gps-telecom
    url: https://www.gps-telecom.com/.well-known/ai-plugin.json
  - name: Gpt.collov
    url: https://gpt.collov.com/.well-known/ai-plugin.json
  - name: GPTWeather
    url: https://gptweather.skirano.repl.co/.well-known/ai-plugin.json
  - name: Greenyroad
    url: https://www.greenyroad.com/.well-known/ai-plugin.json
  - name: Ifttt_action_runs
    url: https://ifttt.com/.well-known/ai-plugin.json
  - name: Influence Marketing
    url: https://influencermarketing.ai/.well-known/ai-plugin.json
  - name: Infobot
    url: https://infobot.ai/.well-known/ai-plugin.json
  - name: Instacart
    url: https://www.instacart.com/.well-known/ai-plugin.json
  - name: Instaforex
    url: https://instaforex.com/.well-known/ai-plugin.json
  - name: Iowa_State_University_Environmental_Mesonet
    url: https://mesonet.agron.iastate.edu/.well-known/ai-plugin.json
  - name: Kalendar
    url: https://kalendar.ai/.well-known/ai-plugin.json
  - name: Kittycad
    url: https://api.kittycad.io/.well-known/ai-plugin.json
  - name: Klarna
    url: https://www.klarna.com/.well-known/ai-plugin.json
  - name: Kyuda
    url: https://www.kyuda.io/.well-known/ai-plugin.json
  - name: Listennotes
    url: https://ai.listennotes.com/.well-known/ai-plugin.json
  - name: Luma
    url: https://lu.ma/.well-known/ai-plugin.json
  - name: Medium
    url: https://medium.com/.well-known/ai-plugin.json
  - name: Meitre
    url: https://meitre.com/.well-known/ai-plugin.json
  - name: Messagebird
    url: https://www.messagebird.com/.well-known/ai-plugin.json
  - name: Milo
    url: https://www.joinmilo.com/.well-known/ai-plugin.json
  - name: Mixerbox
    url: https://www.mixerbox.com/.well-known/ai-plugin.json
  - name: Monitup
    url: https://www.monitup.com/.well-known/ai-plugin.json
  - name: Mrkter
    url: https://mrkter.io/.well-known/ai-plugin.json
  - name: Oneword
    url: https://oneword.domains/.well-known/ai-plugin.json
  - name: OfferZen
    url: https://www.offerzen.com/.well-known/ai-plugin.json
  - name: Openarch
    url: https://www.openarch.nl/.well-known/ai-plugin.json
  - name: Pandia
    url: https://pandia.pro/.well-known/ai-plugin.json
  - name: Parcelsapp
    url: https://parcelsapp.com/.well-known/ai-plugin.json 
  - name: PEForNFTs
    url: https://nftvaluing.com/.well-known/ai-plugin.json
  - name: Placid
    url: https://placid.app/.well-known/ai-plugin.json
  - name: Plugin.so
    url: https://plugin.so/.well-known/ai-plugin.json
  - name: Plugsugar
    url: https://websearch.plugsugar.com/.well-known/ai-plugin.json
  - name: Polarr
    url: https://polarr.co/.well-known/ai-plugin.json
  - name: Polygon
    url: https://polygon.io/.well-known/ai-plugin.json
  - name: Portfoliopilot
    url: https://portfoliopilot.com/.well-known/ai-plugin.json
  - name: Pricerunner
    url: https://www.pricerunner.com/.well-known/ai-plugin.json
  - name: Quickchart
    url: https://quickchart.io/.well-known/ai-plugin.json
  - name: Ramp
    url: https://ramp.com/.well-known/ai-plugin.json
  - name: Redfin
    url: https://www.redfin.com/.well-known/ai-plugin.json
  - name: Remoteambition
    url: https://remoteambition.com/.well-known/ai-plugin.json
  - name: Rentable
    url: https://www.rentable.co/.well-known/ai-plugin.json
  - name: Rescuetime
    url: https://rescuetime.com/.well-known/ai-plugin.json
  - name: Savvytrader
    url: https://savvytrader.com/.well-known/ai-plugin.json
  - name: Scenex
    url: https://scenex.jina.ai/.well-known/ai-plugin.json
  - name: SchoolDigger
    url: https://www.schooldigger.com/.well-known/ai-plugin.json
  - name: Semgrep
    url: https://semgrep.dev/.well-known/ai-plugin.json
  - name: Shop
    url: https://shop.app/.well-known/ai-plugin.json
  - name: SimplyCodes
    url: https://simplycodes.com/.well-known/ai-plugin.json
  - name: Slack
    url: https://slack.com/.well-known/ai-plugin.json
  - name: Stonks
    url: https://stonks.news/.well-known/ai-plugin.json
  - name: Storeya
    url: https://www.storeya.com/.well-known/ai-plugin.json
  - name: Talkface
    url: https://talkface.ai/.well-known/ai-plugin.json
  - name: Tasty
    url: https://tasty.co/.well-known/ai-plugin.json
  - name: Techspecs
    url: https://techspecs.io/.well-known/ai-plugin.json
  - name: Telnyx
    url: https://telnyx.com/.well-known/ai-plugin.json
  - name: Textbelt
    url: https://textbelt.com/.well-known/ai-plugin.json
  - name: Theansible
    url: https://www.theansible.com/.well-known/ai-plugin.json
  - name: Tilnote
    url: https://tilnote.io/.well-known/ai-plugin.json
  - name: Toggle
    url: https://www.junkdoctorsnj.com/.well-known/ai-plugin.json
  - name: Transvribe
    url: https://www.transvribe.com/.well-known/ai-plugin.json
  - name: Trendeer
    url: https://www.trendeer.com/.well-known/ai-plugin.json
  - name: Trip
    url: https://www.trip.com/.well-known/ai-plugin.json
  - name: Triplewhale
    url: https://www.triplewhale.com/.well-known/ai-plugin.json
  - name: Twinkorea
    url: https://twinkorea.io/.well-known/ai-plugin.json
  - name: Twtdata
    url: https://www.twtdata.com/.well-known/ai-plugin.json
  - name: Urlbox
    url: https://urlbox.io/.well-known/ai-plugin.json
  - name: Valispace
    url: https://www.valispace.com/.well-known/ai-plugin.json
  - name: Vbout
    url: https://vbout.com/.well-known/ai-plugin.json
  - name: Video_highlight
    url: https://videohighlight.com/.well-known/ai-plugin.json
  - name: Vidiq
    url: https://api.vidiq.com/.well-known/ai-plugin.json
  - name: wego
    url: https://www.welt.de/.well-known/ai-plugin.json
  - name: welt_news_verse
    url: https://www.welt.de/.well-known/ai-plugin.json
  - name: Whimsical
    url: https://whimsical.com/api/ai-plugin
  - name: Wikiocity
    url: https://www.wikiocity.com/.well-known/ai-plugin.json
  - name: Wikipedia
    url: https://oasst-plugins.dumbserg.al:2083/plugins/wikipedia-plugin.json
  - name: WolframAlpha
    url: https://www.wolframalpha.com/.well-known/ai-plugin.json
  - name: WolframAlphaCloud
    url: https://www.wolframcloud.com/.well-known/ai-plugin.json
  - name: Wordpress
    url: https://wordpress.com/.well-known/ai-plugin.json
  - name: Woxo
    url: https://woxo.tech/.well-known/ai-plugin.json
  - name: Yabble
    url: https://yabblezone.net/.well-known/ai-plugin.json
  - name: Yelp
    url: https://www.yelp.com/.well-known/ai-plugin.json
  - name: Yourtango
    url: https://www.yourtango.com/.well-known/ai-plugin.json
  - name: Zapier
    url: https://zapier.com/.well-known/ai-plugin.json

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: https://targed.github.io/uptest/
  baseUrl: /GPT-Plugins
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Plugins
  introTitle: "Plugins Uptime"
  introMessage: This status page monitors [Plugins](https://github.com/targed/GPT-Plugins) for uptime.
  navbar:
    - title: Status
      href: /GPT-Plugins
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Plugin Information
      href: https://github.com/targed/GPT-Plugins/blob/master/PLUGIN-INFORMATION.md
  theme: dark
